# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 948e362a1b328b5059515a2f0e853b6752da113626ada782f364959abd78740cad260525ec13ba0176f4475a3f2e9bb941399cd326f21d2c44174a9ef1d2a514

test:
  secret_key_base: 26edee6af3dbf48a7d81349143bf2712fe2adf582e6abe0ef2f1c5a8e667e9e9d2bdda87477d052e172f7afb3ec59f52e63df49b3d98ca7c69ddf3647fea6a93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
